CREATE DATABASE BookLibrary
--TAO BANG BOOK
IF OBJECT_ID('BOOK') IS NOT NULL
DROP TABLE BOOK
GO
CREATE TABLE BOOK
(
BOOKCODE INT,
BOOKTITLE VARCHAR(100) NULL,
AUTHOR VARCHAR (50) NOT NULL,
EDITION INT ,
BOOKPRICE MONEY,
COPIES INT
CONSTRAINT PK_BOOK PRIMARY KEY(BOOKCODE)
)
--TAO BANG MEMBER
IF OBJECT_ID ('MEMBER') IS NOT NULL
DROP TABLE MEMBER
GO 
CREATE TABLE MEMBER
(
MEMBERCODE INT ,
NAME VARCHAR(50) NOT NULL,
ADDRESSS VARCHAR(100) NOT NULL,
PHONENUMBER INT
CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBERCODE)
)
IF OBJECT_ID('ISSUEDETAILS') IS NOT NULL
DROP TABLE ISSUEDETAILS
GO
CREATE TABLE ISSUEDETAILS
(
BOOKCODE INT,
MEMBERCODE INT,
ISSUEDETAILS DATETIME,
RETURNDATE  DATETIME
CONSTRAINT FK_BOOK_ISSUEDETAILS FOREIGN KEY(BOOKCODE) REFERENCES BOOK,
CONSTRAINT FK_MEMBER_ISSUEDETAILS FOREIGN KEY(MEMBERCODE) REFERENCES MEMBER
)
--
--A
Alter table ISSUEDETAILS drop constraint
FK_BOOK_ISSUEDETAILS,
FK_MEMBER_ISSUEDETAILS
--B
Alter table MEMBER drop constraint
PK_MEMBER
--
ALTER TABLE BOOK DROP CONSTRAINT
PK_BOOK
--C
Alter TABLE MEMBER

add constraint PK_MEMBER

PRIMARY KEY(MEMBERCODE)
--
Alter TABLE BOOK

add constraint PK_BOOK

PRIMARY KEY(BOOKCODE)
--D
ALTER TABLE ISSUEDETAILS
ADD CONSTRAINT FK_BOOK_ISSUEDETAILS
FOREIGN KEY (BOOKCODE)
REFERENCES BOOK(BOOKCODE)
--
ALTER TABLE ISSUEDETAILS
ADD CONSTRAINT FK_MEMBER_ISSUEDETAILS
FOREIGN KEY (MEMBERCODE)
REFERENCES MEMBER(MEMBERCODE)
--E
ALTER TABLE BOOK
ADD CHECK (200>BOOKPRICE);
--F
ALTER TABLE MEMBER
ADD CONSTRAINT PHONENUMBER1 UNIQUE (PHONENUMBER);
--G
ALTER TABLE ISSUEDETAILS
   MODIFY BOOKCODE  INT NOT NULL;
ALTER TABLE ISSUEDETAILS
   MODIFY MEMBERCODE  INT NOT NULL;
   --H
   ALTER TABLE ISSUEDETAILS
ADD CONSTRAINT PK_ISSUEDETAILS PRIMARY KEY (BOOKCODE);
--
ALTER TABLE ISSUEDETAILS
ADD CONSTRAINT PK_ISSUEDETAILS PRIMARY KEY (MEMBERCODE);
--I
--BANG BOOK
SELECT*FROM BOOK
DELETE FROM BOOK
INSERT INTO BOOK VALUES('100','DONG VAT','RONALDO','12','100','120')
INSERT INTO BOOK VALUES('101','THE GIOI','MESSI','13','100','220')
INSERT INTO BOOK VALUES('102','AN NINH','SILVA','14','100','220')
--BANG MEMBER
SELECT * FROM MEMBER
DELETE FROM MEMBER
INSERT INTO MEMBER VALUES ('12','PHAN','NAM DINH','012633638')
INSERT INTO MEMBER VALUES ('13','HAI','HA NOI','0126336358')
INSERT INTO MEMBER VALUES ('14','TUAN','HA NAM','0126334638')
--BANG ISSUEDETAILS
SELECT * FROM ISSUEDETAILS
DELETE FROM ISSUEDETAILS
INSERT INTO ISSUEDETAILS VALUES ('100','13','2012-7-5','2013-7-5')
INSERT INTO ISSUEDETAILS VALUES ('101','12','2013-8-5','2013-8-5')
INSERT INTO ISSUEDETAILS VALUES ('102','14','2015-9-5','2013-7-5')
--
SELECT * FROM BOOK
SELECT * FROM MEMBER
SELECT * FROM ISSUEDETAILS

